language: android
android:
        components:
                - platform-tools
                - build-tools-21.0.1
                - android-21
                - extra-android-m2repository
script:
        - ./Wilenco_App/gradlew build
        - java Wilenco_App\app\src\test\java\com\example\kattyadesiderio\wilencoapp\ExampleUnitTest
before_install:
        - chmod +x Wilenco_App/gradlew
branches:
        only:
                - master
