language: android
android:
        components:
                - platform-tools
                - build-tools-21.0.1
                - android-21
                - extra-android-m2repository
script:
        - ./MyApplication/gradlew build
        - cd MyApplication/app/src/test/java/com/example/kattyadesiderio/wilencoapp
        - javac ExampleUnitTest.java
        - java -cp .:/usr/share/java/junit.jar ExampleUnitTest
        
before_install:
        - chmod +x MyApplication/gradlew
branches:
        only:
                - master
